#服务器端口号
server:
    port: 21080
#数据源基本配置信息
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev?characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    logSlowSql: true
    #访问：http://localhost:port/domain/druid/login.html 进行登录访问。


  #JPA配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql

  jackson:
    serialization:
      indent_output: false

#mybatis配置
#mybatis:
  #type-aliases-package: com.limo_vue.domain
  #config-location: classpath:mybatis/mybatis-config.xml
  #mapper-locations: com.limo_vue.dao
  #mapper-locations: com.limo_vue.dao

  #logback配置
logging:
  #定义日志文件的存储地址
  file: log.log
  #config: classpath:logback-dev.xml
